services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    expose:
      - 8080
    networks:
      - perplexica-network
    healthcheck:
      test: ['CMD-SHELL', 'pgrep -f searxng']
      <<: *default-healthcheck
  perplexica:
    image: nvroot/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://${DOMAIN}/api
        - NEXT_PUBLIC_WS_URL=wss://${DOMAIN}/api
    restart: unless-stopped
    container_name: perplexica
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
    expose:
      - 3000
    networks:
      - perplexica-network
      - proxy
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml

networks:
  perplexica-network:
  proxy:
    external: true
volumes:
  backend-dbstore:
  uploads:
